//liste des villes de Madagascar
const List<String> madagascarCities = [
  'Antananarivo',
  'Toamasina',
  'Antsirabe',
  'Fianarantsoa',
  'Mahajanga',
  'Toliara',
  'Antsiranana',
  'Ambovombe',
  'Morondava',
  'Moramanga',
  'Ambatondrazaka',
  'Mananjary',
  'Manakara',
  'Farafangana',
  'Fort-Dauphin (Tôlanaro)',
  'Tsiroanomandidy',
  'Maevatanana',
  'Maintirano',
  'Morombe',
  'Ambanja',
  'Nosy Be (Hell-Ville)',
  'Sambava',
  'Antalaha',
  'Vohemar',
];